# Generated by Django 4.2 on 2023-04-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Amarelo", "Amarelo"),
                            ("Azul", "Azul"),
                            ("Cinza", "Cinza"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Hatch", "Hatch"),
                            ("Sedã", "Sedã"),
                            ("Conversivel", "Conversivel"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Nome")),
                ("lastname", models.CharField(max_length=15, verbose_name="Sobrenome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("cellphone", models.CharField(max_length=15, verbose_name="Celular")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em:"
                    ),
                ),
                ("owner_car", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Owner_Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management_cars_city.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management_cars_city.color",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management_cars_city.model",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management_cars_city.owner_cars",
                    ),
                ),
            ],
        ),
    ]
