# Generated by Django 4.2 on 2023-04-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management_cars_city", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner_cars",
            name="owner",
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                choices=[("Amarelo", "Amarelo"), ("Azul", "Azul"), ("Cinza", "Cinza")]
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(
                choices=[
                    ("Hatch", "Hatch"),
                    ("Sedã", "Sedã"),
                    ("Conversivel", "Conversivel"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="management_cars_city.person",
            ),
        ),
        migrations.DeleteModel(
            name="Color",
        ),
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.DeleteModel(
            name="Owner_Cars",
        ),
    ]
