# Generated by Django 4.2 on 2023-04-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_cars_city",
            "0002_remove_owner_cars_owner_alter_car_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(verbose_name="Cadastrado em:"),
        ),
    ]
