# Generated by Django 4.2 on 2023-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_cars_city", "0003_alter_person_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Cadastrado em:"
            ),
        ),
    ]
