# Generated by Django 4.2 on 2023-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_cars_city", "0004_alter_person_created"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("owner", "color", "model")},
        ),
    ]
