# Generated by Django 4.2 on 2023-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_cars_city', '0005_alter_car_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Amarelo', 'Amarelo'), ('Azul', 'Azul'), ('Cinza', 'Cinza')], max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Hatch', 'Hatch'), ('Sedã', 'Sedã'), ('Conversivel', 'Conversivel')], max_length=12),
        ),
    ]
