# Generated by Django 4.2 on 2023-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_cars_city", "0007_alter_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
    ]
