# Generated by Django 4.2 on 2023-05-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_cars_city", "0008_alter_person_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("owner", "model", "color")},
        ),
    ]
